### PR TITLE
Added gitignore for common files

### PR DESCRIPTION
**Pull request by TheKnarf**
The gitignore ignores common operating system, common tools related to
JavaScript development and common development editors and IDE's.

List over OS, tools and editors/IDE's which are added to the .gitignore:

```
- osx
- windows
- linux
- bower
- node
- grunt
- sublimetext
- intellij
- vim
```

### CODE REVIEW

**Comment by TheKnarf** [comment]
I updated the PR so that is doesn't have any merge conflicts.

I'd love some feedback on what you think @jagenjo.

**Comment by jagenjo** [comment]
great :+1:

**Comment by TheKnarf** [comment]
Did you just comment `great 👍`, and then close my pull request but not merge it?

**Comment by jagenjo** [comment]
It is merged

**Comment by jagenjo** [comment]
wait, it isnt, weird, I clicked the merge button

**Comment by TheKnarf** [comment]
Perhaps you mistakingly clicked `close` instead of `merge`? I'll try creating a new PR

**Comment by jagenjo** [comment]
I totally clicked merged and it asked me the merge message. I do not understand git sometimes.

**Pull request closed without merging**
